import type { SourceRef } from "@/components/ui";
import type { Election, ElectionResult, NextElection } from "@/lib/eleicoes/types";

/**
 * Most recent election of each type. All figures come from the CNE mapas oficiais published in the
 * Diário da República, unless a note says a figure was derived. Research notes: docs/research/eleicoes.md.
 */

const CHECKED = "2026-09-13";
const CRP: SourceRef = {
  title: "Constituição da República Portuguesa, Assembleia da República",
  url: "https://www.parlamento.pt/Legislacao/Paginas/ConstituicaoRepublicaPortuguesa.aspx",
  verifiedOn: CHECKED,
  verification: "primary",
};
const src = (title: string, url: string, verification: "primary" | "derived" = "primary"): SourceRef => ({ title, url, verifiedOn: CHECKED, verification });

function r(name: string, short: string, votes: number | null, pct: number | null, seats: number | null = null, previousSeats: number | null = null, elected: boolean | null = null): ElectionResult {
  return { name, short, votes, pct, seats, previousSeats, elected };
}

export const ELECTIONS: Election[] = [
  {
    id: "presidenciais-2026",
    type: "presidenciais",
    title: "Presidenciais 2026",
    chooses: "Escolhe o Presidente da República, por 5 anos.",
    measure: "votes",
    seatsTotal: null,
    rounds: [
      {
        label: "1.ª volta",
        date: "2026-01-18",
        registered: 11009803,
        voters: 5768536,
        turnoutPct: 52.39,
        blank: 61275,
        null: 64565,
        results: [
          r("António José Martins Seguro", "António José Seguro", 1755563, 31.11),
          r("André Claro Amaral Ventura", "André Ventura", 1327021, 23.52),
          r("João Fernando Cotrim de Figueiredo", "João Cotrim de Figueiredo", 903057, 16.0),
          r("Henrique Eduardo Passaláqua de Gouveia e Melo", "Henrique Gouveia e Melo", 695377, 12.32),
          r("Luís Manuel Gonçalves Marques Mendes", "Luís Marques Mendes", 637442, 11.3),
          r("Catarina Soares Martins", "Catarina Martins", 116407, 2.06),
          r("António Filipe Gaião Rodrigues", "António Filipe", 92644, 1.64),
          r("Manuel João Gonçalves Rodrigues Vieira", "Manuel João Vieira", 60927, 1.08),
          r("Eduardo Jorge Costa Pinto", "Jorge Pinto", 38588, 0.68),
          r("André Pestana da Silva", "André Pestana", 10897, 0.19),
          r("Humberto Raimundo Joaquim Correia", "Humberto Correia", 4773, 0.08),
        ],
      },
      {
        label: "2.ª volta",
        date: "2026-02-08",
        registered: 11025823,
        voters: 5515977,
        turnoutPct: 50.03,
        blank: 177072,
        null: 98342,
        results: [r("António José Martins Seguro", "António José Seguro", 3502613, 66.84, null, null, true), r("André Claro Amaral Ventura", "André Ventura", 1737950, 33.16, null, null, false)],
      },
    ],
    scope: "Portugal e eleitores recenseados no estrangeiro, num único círculo nacional. As percentagens são dos votos válidos: os votos em branco e nulos não contam.",
    meaning: [
      "Na 1.ª volta nenhum candidato teve mais de metade dos votos válidos. Por isso, os dois mais votados foram a uma 2.ª volta, três semanas depois.",
      "António José Seguro foi eleito na 2.ª volta, com 66,84% dos votos válidos. Tomou posse a 9 de março de 2026.",
      "O Presidente não governa. Nomeia o Primeiro-Ministro depois de ouvir os partidos, promulga ou veta leis e pode dissolver a Assembleia da República.",
      "Votou cerca de metade dos inscritos nas duas voltas. Na 2.ª volta houve quase três vezes mais votos em branco do que na 1.ª.",
    ],
    system: [
      "Há um só círculo eleitoral para todo o país e para quem vive no estrangeiro (Lei Eleitoral do Presidente da República, art. 7.º).",
      "Ganha quem tiver mais de metade dos votos válidos. Se ninguém tiver, os dois mais votados vão a uma 2.ª volta (Constituição, art. 126.º).",
      "O mandato dura 5 anos e não pode haver um terceiro mandato seguido (Constituição, arts. 123.º e 128.º).",
      "Um candidato precisa de 7 500 a 15 000 assinaturas de eleitores, de ser português de origem e de ter mais de 35 anos (Constituição, arts. 122.º e 124.º).",
    ],
    sources: [
      src("CNE, Mapa Oficial n.º 1-A/2026, 1.ª volta", "https://www.cne.pt/sites/default/files/dl/eleicoes/2026_pr/docs_geral/2026_pr_1-sufragio_mapa_oficial_dr.pdf"),
      src("CNE, Mapa Oficial n.º 1/2026, 2.ª volta", "https://www.cne.pt/sites/default/files/dl/eleicoes/2026_pr/docs_geral/2026_pr_2-sufragio_mapa_oficial_dr.pdf"),
      src("CNE, Lei Eleitoral do Presidente da República, versão consolidada", "https://www.cne.pt/sites/default/files/dl/legis_lepr_consolidada_2026-07.pdf"),
      CRP,
    ],
    notes: [
      "Os nomes curtos são os nomes pelos quais os candidatos são conhecidos. O nome completo é o do mapa oficial.",
      "O mapa oficial da 2.ª volta assinala pequenas diferenças na contagem de inscritos e de votos em alguns locais. Os totais publicados são os oficiais.",
    ],
  },
  {
    id: "legislativas-2025",
    type: "legislativas",
    title: "Legislativas 2025",
    chooses: "Elege os 230 deputados da Assembleia da República. Da nova Assembleia sai o Governo.",
    measure: "votes",
    seatsTotal: 230,
    previousLabel: "2024",
    rounds: [
      {
        label: "Votação",
        date: "2025-05-18",
        registered: 10848816,
        voters: 6319969,
        turnoutPct: 58.25,
        blank: 87654,
        null: 172994,
        results: [
          { ...r("PPD/PSD.CDS-PP — AD — COLIGAÇÃO PSD/CDS", "AD (PSD/CDS)", 1971602, 32.54, 88, 77), previousNote: "A lista AD de 2024 não concorreu na Madeira e a de 2025 não concorreu nos Açores. A comparação não é exata. Somando as listas PSD/CDS de cada ano: 80 deputados em 2024 e 91 em 2025." },
          r("PS — Partido Socialista", "PS", 1442546, 23.81, 58, 78),
          r("CH — CHEGA", "Chega", 1438554, 23.74, 60, 50),
          r("IL — Iniciativa Liberal", "IL", 338974, 5.59, 9, 8),
          r("L — LIVRE", "Livre", 257291, 4.25, 6, 4),
          r("PCP-PEV — CDU — Coligação Democrática Unitária", "CDU", 183686, 3.03, 3, 4),
          r("B.E. — Bloco de Esquerda", "BE", 125808, 2.08, 1, 5),
          r("PAN — PESSOAS — ANIMAIS — NATUREZA", "PAN", 86930, 1.43, 1, 1),
          r("ADN — ALTERNATIVA DEMOCRÁTICA NACIONAL", "ADN", 81660, 1.35, 0, 0),
          r("PPD/PSD.CDS-PP.PPM — PSD/CDS/PPM", "PSD/CDS/PPM (Açores)", 36886, 0.61, 3, null),
          r("JPP — Juntos Pelo Povo", "JPP", 20900, 0.34, 1, 0),
        ],
      },
    ],
    scope: "Portugal e os dois círculos da emigração. Mostramos as listas com pelo menos um deputado e as outras com 1% ou mais. As percentagens são dos votos válidos.",
    meaning: [
      "Nenhuma lista teve maioria absoluta, que são 116 dos 230 deputados. As duas listas PSD/CDS somaram 91 deputados.",
      "Sem maioria absoluta, o Governo precisa do voto a favor ou da abstenção de outros partidos para aprovar leis e o Orçamento do Estado.",
      "O PS teve mais votos do que o Chega, mas menos deputados. Os lugares são distribuídos em cada círculo eleitoral, não pelo total do país.",
      "Esta Assembleia é a XVII Legislatura. O Governo que dela saiu é liderado por Luís Montenegro.",
    ],
    system: [
      "Há 22 círculos: 18 distritos do continente, Açores, Madeira e dois círculos da emigração, Europa e Fora da Europa (Lei Eleitoral da AR, art. 12.º).",
      "Os círculos do território nacional dividem 226 lugares conforme o número de eleitores. Cada círculo da emigração elege 2 (art. 13.º).",
      "Cada eleitor vota numa lista fechada. Os lugares de cada círculo são distribuídos pelo método de D'Hondt (arts. 14.º e 16.º).",
      "Uma legislatura dura 4 anos. A Assembleia não pode ser dissolvida nos 6 meses depois da eleição (Constituição, arts. 171.º e 172.º).",
    ],
    sources: [
      src("CNE, Mapa Oficial n.º 2-A/2025, legislativas de 18 de maio de 2025", "https://www.cne.pt/sites/default/files/dl/eleicoes/2025_ar/2025_ar_mapa_oficial_dr.pdf"),
      src("CNE, Mapa Oficial n.º 2-A/2024, legislativas de 10 de março de 2024", "https://www.cne.pt/sites/default/files/dl/2024_ar_mapa_oficial_dr.pdf"),
      src("CNE, Lei Eleitoral da Assembleia da República, versão consolidada", "https://www.cne.pt/sites/default/files/dl/legis_lear_consolidada_2026-07.pdf"),
      CRP,
    ],
    notes: [
      "Em 2024 e 2025 o PSD e o CDS concorreram com nomes de lista diferentes em cada região. Em 2024: 77 deputados da AD e 3 da lista Madeira Primeiro, 80 no total. Em 2025: 88 da AD e 3 da lista dos Açores, 91 no total. A coluna 2024 da AD mostra os 77, que não cobrem exatamente os mesmos círculos.",
      "O total de 91 deputados e 2 008 488 votos das duas listas PSD/CDS é uma soma nossa das linhas do mapa oficial.",
    ],
  },
  {
    id: "europeias-2024",
    type: "europeias",
    title: "Europeias 2024",
    chooses: "Elege os 21 deputados portugueses ao Parlamento Europeu, por 5 anos.",
    measure: "votes",
    seatsTotal: 21,
    rounds: [
      {
        label: "Votação",
        date: "2024-06-09",
        registered: 10789781,
        voters: 3951979,
        turnoutPct: 36.63,
        blank: 47477,
        null: 29731,
        results: [
          r("Partido Socialista", "PS", 1268915, 32.75, 8),
          r("AD — ALIANÇA DEMOCRÁTICA", "AD (PSD/CDS/PPM)", 1229895, 31.74, 7),
          r("CHEGA", "Chega", 387068, 9.99, 2),
          r("Iniciativa Liberal", "IL", 358811, 9.26, 2),
          r("Bloco de Esquerda", "BE", 168107, 4.34, 1),
          r("CDU — Coligação Democrática Unitária", "CDU", 162630, 4.2, 1),
          r("LIVRE", "Livre", 148572, 3.83, 0),
          r("ALTERNATIVA DEMOCRÁTICA NACIONAL", "ADN", 54120, 1.4, 0),
          r("PESSOAS-ANIMAIS-NATUREZA", "PAN", 48006, 1.24, 0),
          r("Volt Portugal", "Volt", 9445, 0.24, 0),
          r("Ergue-te", "Ergue-te", 8302, 0.21, 0),
          r("Reagir Incluir Reciclar", "RIR", 6407, 0.17, 0),
          r("NOVA DIREITA", "Nova Direita", 6361, 0.16, 0),
          r("Movimento Alternativa Socialista", "MAS", 5016, 0.13, 0),
          r("Partido da Terra", "MPT", 4558, 0.12, 0),
          r("Partido Trabalhista Português", "PTP", 4312, 0.11, 0),
          r("Nós, Cidadãos!", "Nós, Cidadãos!", 4246, 0.11, 0),
        ],
      },
    ],
    scope: "Um único círculo nacional. Inclui portugueses no estrangeiro que não votaram noutro país da União Europeia. As percentagens são dos votos válidos.",
    meaning: [
      "O PS foi a lista mais votada e elegeu 8 deputados. A AD elegeu 7.",
      "No Parlamento Europeu, os deputados sentam-se em grupos políticos europeus, não por país. O Parlamento aprova, com os governos da União Europeia, a maior parte das leis europeias e o orçamento europeu.",
      "Votaram 36,63% dos inscritos. É a participação mais baixa das eleições desta página.",
    ],
    system: [
      "Há um único círculo nacional (Lei Eleitoral do Parlamento Europeu, art. 2.º).",
      "Podem votar os portugueses recenseados em Portugal, os que vivem no estrangeiro e não votam noutro país da UE, e os cidadãos da UE recenseados em Portugal (art. 3.º).",
      "Os lugares são distribuídos pelo método de D'Hondt, como nas legislativas (art. 1.º e Lei Eleitoral da AR, art. 16.º).",
      "Em 2024 foi possível votar em mobilidade no dia da eleição, em qualquer mesa em Portugal ou no estrangeiro (Lei n.º 80/2023).",
    ],
    sources: [
      src("CNE, Mapa Oficial n.º 4/2024, europeias de 9 de junho de 2024", "https://www.cne.pt/sites/default/files/dl/eleicoes/2024_pe/docs_geral/2024_pe_mapa_oficial_resultados_dr.pdf"),
      src("CNE, Lei Eleitoral do Parlamento Europeu", "https://www.cne.pt/sites/default/files/dl/legis_lepe_atualiz-2022.pdf"),
    ],
    notes: ["Os resultados de 2019 não estão incluídos, por isso não mostramos a variação de deputados."],
  },
  {
    id: "autarquicas-2025",
    type: "autarquicas",
    title: "Autárquicas 2025",
    chooses: "Elege as câmaras municipais, as assembleias municipais e as assembleias de freguesia dos 308 municípios, por 4 anos.",
    measure: "councils",
    seatsTotal: 308,
    previousLabel: "2021",
    groups: {
      label: "Câmaras ganhas, por partido",
      note: "Os partidos concorrem muitas vezes em coligações diferentes em cada município. Aqui juntamos cada coligação ao partido que dela faz parte: PS com as listas em que o PS participa, PSD com as listas em que o PSD participa.",
      results: [
        r("PPD/PSD e coligações com o PSD", "PSD e coligações", null, null, 136, 113),
        r("PS e coligações com o PS", "PS e coligações", null, null, 128, 149),
        r("Grupos de cidadãos eleitores", "Independentes", null, null, 20, 19),
        r("PCP-PEV (CDU)", "CDU", null, null, 12, 19),
        r("CDS-PP, sozinho", "CDS", null, null, 6, 6),
        r("CH — CHEGA", "Chega", null, null, 3, 0),
        r("NC e NC.PPM", "Nós, Cidadãos!", null, null, 2, 0),
        r("JPP — Juntos Pelo Povo", "JPP", null, null, 1, 1),
        r("A — Aliança", "Aliança", null, null, 0, 1),
      ],
    },
    rounds: [
      {
        label: "Votação",
        date: "2025-10-12",
        registered: 9300840,
        voters: 5514304,
        turnoutPct: 59.29,
        blank: 95742,
        null: 64004,
        results: [
          r("PS", "PS", null, null, 126, 148),
          r("PPD/PSD", "PSD", null, null, 78, 72),
          r("PPD/PSD.CDS-PP", "PSD/CDS", null, null, 44, 30),
          r("Grupos de cidadãos eleitores", "Independentes", null, null, 20, 19),
          r("PCP-PEV", "CDU", null, null, 12, 19),
          r("CDS-PP", "CDS", null, null, 6, 6),
          r("PPD/PSD.CDS-PP.PPM", "PSD/CDS/PPM", null, null, 4, 3),
          r("PPD/PSD.CDS-PP.IL", "PSD/CDS/IL", null, null, 4, null),
          r("CH", "Chega", null, null, 3, 0),
          r("JPP", "JPP", null, null, 1, 1),
          r("NC", "Nós, Cidadãos!", null, null, 1, 0),
          r("NC.PPM", "NC/PPM", null, null, 1, null),
          r("PS.L.PAN", "PS/Livre/PAN", null, null, 1, null),
          r("L.PS", "Livre/PS", null, null, 1, 1),
          r("PPD/PSD.MPT", "PSD/MPT", null, null, 1, 1),
          r("PPD/PSD.IL", "PSD/IL", null, null, 1, null),
          r("PPD/PSD.IL.PAN", "PSD/IL/PAN", null, null, 1, null),
          r("PPD/PSD.CDS-PP.MPT.PPM", "PSD/CDS/MPT/PPM", null, null, 1, 2),
          r("PPD/PSD.CDS-PP.PPM.MPT", "PSD/CDS/PPM/MPT", null, null, 1, null),
          r("PPD/PSD.CDS-PP.VP", "PSD/CDS/Volt", null, null, 1, null),
        ],
      },
    ],
    scope: "Presidências de câmara municipal ganhas em 308 municípios, não vereadores. A CNE publica os resultados de cada município. Os totais nacionais desta página são contagens nossas a partir desses resultados.",
    meaning: [
      "Em cada município, o presidente da câmara é o primeiro candidato da lista mais votada para a câmara municipal.",
      "As listas com o PSD ganharam 136 câmaras, mais 23 do que em 2021. As listas com o PS ganharam 128, menos 21.",
      "As câmaras gerem serviços do dia a dia: urbanismo e licenças de obras, recolha de lixo, água em muitos municípios, escolas do 1.º ciclo, transportes locais e apoio social.",
      "Os grupos de cidadãos, sem partido, ganharam 20 câmaras, entre elas Oeiras, Setúbal e Mafra.",
    ],
    system: [
      "Vota-se em três boletins: câmara municipal, assembleia municipal e assembleia de freguesia (Lei Eleitoral dos Órgãos das Autarquias Locais, art. 11.º).",
      "Podem concorrer partidos, coligações e grupos de cidadãos eleitores.",
      "Os lugares são distribuídos pelo método de D'Hondt (art. 13.º).",
      "O presidente da câmara é o primeiro nome da lista mais votada (Lei n.º 169/99, art. 57.º).",
    ],
    sources: [
      src("CNE, Mapa Oficial n.º 2-B/2025, autárquicas de 12 de outubro de 2025", "https://www.cne.pt/sites/default/files/dl/eleicoes/2025_al/docs_geral/2025_al_mapa_oficial_dr.pdf"),
      src("CNE, mapa oficial retificado em folha de cálculo (contagem por município)", "https://www.cne.pt/sites/default/files/dl/eleicoes/2025_al/docs_geral/2025al-mapa-oficial_retificado.zip", "derived"),
      src("CNE, Mapa Oficial n.º 1-B/2021, autárquicas de 2021, folhas de cálculo", "https://www.cne.pt/sites/default/files/dl/2021al_mapa_oficial.zip", "derived"),
      src("CNE, Lei Eleitoral dos Órgãos das Autarquias Locais", "https://www.cne.pt/sites/default/files/dl/legis_leoal_2021_06_04.pdf"),
    ],
    notes: [
      "A CNE não publica um total nacional de câmaras por partido. Contámos a lista mais votada para a câmara em cada um dos 308 municípios, a partir do mapa oficial retificado.",
      "A participação (59,29%), os inscritos e os votos em branco e nulos também são somas nossas dos 308 municípios.",
      "Em 2021 a Aliança ganhou 1 câmara (Amarante). Em 2025 não ganhou nenhuma.",
      "Algumas coligações de 2025 não existiam em 2021 com a mesma composição. Nesses casos a coluna 2021 fica vazia.",
    ],
  },
  {
    id: "regionais-acores-2024",
    type: "regionais",
    title: "Regionais dos Açores 2024",
    chooses: "Elege os 57 deputados da Assembleia Legislativa dos Açores. Dela sai o Governo Regional.",
    measure: "votes",
    seatsTotal: 57,
    rounds: [
      {
        label: "Votação",
        date: "2024-02-04",
        registered: 229909,
        voters: 115655,
        turnoutPct: 50.3,
        blank: 2522,
        null: 1407,
        results: [
          r("PPD/PSD.CDS-PP.PPM — PSD/CDS/PPM", "PSD/CDS/PPM", 48672, 43.56, 26),
          r("PS — Partido Socialista", "PS", 41538, 37.18, 23),
          r("CH — CHEGA", "Chega", 10627, 9.51, 5),
          r("B.E. — Bloco de Esquerda", "BE", 2936, 2.63, 1),
          r("IL — Iniciativa Liberal", "IL", 2482, 2.22, 1),
          r("PAN — PESSOAS-ANIMAIS-NATUREZA", "PAN", 1907, 1.71, 1),
          r("PCP-PEV — CDU — Coligação Democrática Unitária", "CDU", 1821, 1.63, 0),
          r("L — LIVRE", "Livre", 735, 0.66, 0),
          r("JPP — Juntos pelo Povo", "JPP", 626, 0.56, 0),
          r("ADN — ALTERNATIVA DEMOCRÁTICA NACIONAL", "ADN", 378, 0.34, 0),
        ],
      },
    ],
    scope: "Nove círculos de ilha e um círculo regional de compensação. As percentagens são dos votos válidos.",
    meaning: [
      "A coligação PSD/CDS/PPM foi a mais votada e elegeu 26 deputados. A maioria absoluta são 29.",
      "Sem maioria absoluta, o Governo Regional precisa do apoio de outros partidos para aprovar o orçamento e os planos da região.",
      "A Assembleia Legislativa faz leis sobre assuntos da região, dentro dos limites da Constituição e do Estatuto dos Açores.",
    ],
    system: [
      "A Assembleia tem no máximo 57 deputados (Lei Eleitoral da Assembleia Legislativa dos Açores, art. 11.º-A).",
      "Cada uma das 9 ilhas é um círculo. Há ainda um círculo regional de compensação, que elege 5 deputados (arts. 12.º e 13.º).",
      "O círculo de compensação usa o método de D'Hondt e tem em conta os lugares já ganhos nas ilhas. Dá mais peso ao total de votos da região (art. 16.º).",
    ],
    sources: [
      src("CNE, Mapa Oficial n.º 1-B/2024, regionais dos Açores de 4 de fevereiro de 2024", "https://www.cne.pt/sites/default/files/dl/eleicoes/2024_alraa/docs_geral/2024_alraa_mapa_oficial_resultados.pdf"),
      src("CNE, Lei Eleitoral da Assembleia Legislativa dos Açores, republicada", "https://www.cne.pt/sites/default/files/dl/legis_lealraa_republicada_10-09-2026.pdf"),
    ],
    notes: ["BE, IL e PAN elegeram os seus deputados só no círculo de compensação. Os resultados de 2020 não estão incluídos."],
  },
  {
    id: "regionais-madeira-2025",
    type: "regionais",
    title: "Regionais da Madeira 2025",
    chooses: "Elege os 47 deputados da Assembleia Legislativa da Madeira. Dela sai o Governo Regional.",
    measure: "votes",
    seatsTotal: 47,
    rounds: [
      {
        label: "Votação",
        date: "2025-03-23",
        registered: 255380,
        voters: 142959,
        turnoutPct: 55.98,
        blank: 715,
        null: 2581,
        results: [
          r("Partido Social Democrata", "PSD", 62059, 44.43, 23),
          r("Juntos pelo Povo", "JPP", 30091, 21.55, 11),
          r("Partido Socialista", "PS", 22351, 16.0, 8),
          r("CHEGA", "Chega", 7821, 5.6, 3),
          r("CDS — Partido Popular", "CDS", 4289, 3.07, 1),
          r("Iniciativa Liberal", "IL", 3097, 2.22, 1),
          r("CDU — Coligação Democrática Unitária", "CDU", 2543, 1.82, 0),
          r("PESSOAS — ANIMAIS — NATUREZA", "PAN", 2323, 1.66, 0),
          r("Bloco de Esquerda", "BE", 1586, 1.14, 0),
          r("LIVRE", "Livre", 959, 0.69, 0),
          r("FORÇA MADEIRA", "Força Madeira", 790, 0.57, 0),
          r("ALTERNATIVA DEMOCRÁTICA NACIONAL", "ADN", 691, 0.49, 0),
          r("Partido Popular Monárquico", "PPM", 576, 0.41, 0),
          r("NOVA DIREITA", "Nova Direita", 487, 0.35, 0),
        ],
      },
    ],
    scope: "Um único círculo para toda a região. As percentagens são dos votos válidos.",
    meaning: [
      "O PSD foi o mais votado e elegeu 23 deputados, a um da maioria absoluta, que são 24.",
      "O JPP, um partido nascido na Madeira, ficou em segundo lugar, com 11 deputados.",
      "A Assembleia Legislativa faz leis sobre assuntos da região e aprova o orçamento regional.",
    ],
    system: [
      "Os 47 deputados são eleitos num único círculo, pelo método de D'Hondt (Lei Eleitoral da Assembleia Legislativa da Madeira, arts. 11.º e 12.º).",
      "As eleições de uma nova legislatura são entre 22 de setembro e 14 de outubro do ano em que a legislatura acaba (art. 19.º). Uma dissolução pode antecipar a data.",
    ],
    sources: [
      src("CNE, Mapa Oficial n.º 2/2025, regionais da Madeira de 23 de março de 2025", "https://www.cne.pt/sites/default/files/dl/eleicoes/2025_alram/docs_geral/2025_alram_mapa_oficial_dre.pdf"),
      src("CNE, Lei Eleitoral da Assembleia Legislativa da Madeira", "https://www.cne.pt/sites/default/files/dl/legis_lealram_atualizada.pdf"),
    ],
    notes: ["Os resultados de 2024 não estão incluídos, por isso não mostramos a variação de deputados."],
  },
  {
    id: "referendo-2007",
    type: "referendo",
    title: "Referendo nacional 2007",
    chooses: "Perguntou se a interrupção voluntária da gravidez devia deixar de ser crime nas primeiras 10 semanas, por opção da mulher, em estabelecimento de saúde autorizado.",
    measure: "votes",
    seatsTotal: null,
    rounds: [
      {
        label: "Votação",
        date: "2007-02-11",
        registered: 8814016,
        voters: 3840176,
        turnoutPct: 43.57,
        blank: 48094,
        null: 25884,
        results: [r("Sim", "Sim", 2231529, 59.25, null, null, true), r("Não", "Não", 1534669, 40.75, null, null, false)],
      },
    ],
    scope: "Eleitores recenseados em território nacional. As percentagens são dos votos válidos.",
    meaning: [
      "Ganhou o «Sim», com 59,25% dos votos válidos.",
      "O resultado não foi vinculativo, porque votaram menos de metade dos inscritos (43,57%). Um referendo só obriga quando vota mais de metade (Constituição, art. 115.º).",
      "É o referendo nacional mais recente. Depois de 2007 houve apenas referendos locais.",
    ],
    system: [
      "O Presidente da República decide convocar um referendo, sob proposta da Assembleia da República ou do Governo (Constituição, art. 115.º).",
      "As perguntas têm de ter resposta «sim» ou «não».",
      "Os portugueses no estrangeiro só votam quando o tema lhes diz especificamente respeito.",
    ],
    sources: [src("CNE, Mapa Oficial n.º 1/2007, referendo nacional de 11 de fevereiro de 2007", "https://www.cne.pt/sites/default/files/dl/resultados_rn_1_2007.pdf"), CRP],
    notes: [],
  },
];

export const NEXT_ELECTIONS: NextElection[] = [
  { type: "legislativas", label: "Legislativas", date: null, latestBy: "setembro ou outubro de 2029", basis: "Constituição, art. 171.º; Lei Eleitoral da AR, art. 19.º. Uma dissolução pode antecipar." },
  { type: "europeias", label: "Europeias", date: null, latestBy: "maio ou junho de 2029", basis: "Mandato europeu de 5 anos; o período é fixado pela União Europeia." },
  { type: "autarquicas", label: "Autárquicas", date: null, latestBy: "setembro ou outubro de 2029", basis: "Lei Eleitoral das Autarquias, art. 15.º: entre 22 de setembro e 14 de outubro." },
  { type: "regionais", label: "Regionais dos Açores", date: null, latestBy: "setembro ou outubro de 2028", basis: "Lei Eleitoral da Assembleia Legislativa dos Açores, art. 19.º. Uma dissolução pode antecipar." },
  { type: "regionais", label: "Regionais da Madeira", date: null, latestBy: "setembro ou outubro de 2029", basis: "Lei Eleitoral da Assembleia Legislativa da Madeira, art. 19.º. Uma dissolução pode antecipar." },
  { type: "presidenciais", label: "Presidenciais", date: null, latestBy: "janeiro de 2031", basis: "Constituição, arts. 125.º e 128.º: nos 60 dias antes do fim do mandato de 5 anos." },
];

export const WHO_CAN_VOTE = [
  "Podem votar os cidadãos portugueses com 18 anos ou mais. Votar é pessoal e é um dever cívico (Constituição, art. 49.º).",
  "O recenseamento é automático: quem tem Cartão de Cidadão fica inscrito aos 17 anos e pode votar se fizer 18 até ao dia da eleição (Lei n.º 13/99).",
  "Nas presidenciais e nas legislativas, quem está recenseado em território nacional pode pedir para votar antes do dia da eleição, noutro local (voto antecipado em mobilidade).",
];

export const getElection = (id: string) => ELECTIONS.find((e) => e.id === id) ?? null;
